stages:
  - deploy

deploy_prod:
  stage: deploy
  image: google/cloud-sdk:alpine
  environment: PROD
  only:
    refs:
      - main
    changes:
      - frontend/**/*
  script:
  - echo $GCP_CLOUD_BUILD_SERVICE_KEY > /tmp/gcloud-service-key.json
  - gcloud auth activate-service-account --key-file /tmp/gcloud-service-key.json
  - gcloud config set project $GCP_PROJECT_ID
  - gcloud builds submit . --config cloudbuild.yaml
  
  after_script:
    - rm /tmp/gcloud-service-key.json

deploy_admin:
  stage: deploy
  image: google/cloud-sdk:alpine
  environment: PROD
  only:
    refs:
      - main
    changes:
      - adminportal/**/*
  script:
  - echo $GCP_CLOUD_BUILD_SERVICE_KEY > /tmp/gcloud-service-key.json
  - gcloud auth activate-service-account --key-file /tmp/gcloud-service-key.json
  - gcloud config set project $GCP_PROJECT_ID
  - gcloud builds submit . --config cloudbuild_admin.yaml
  after_script:
  - rm /tmp/gcloud-service-key.json