steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sdp4-admin', './adminportal']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sdp4-admin']

  - name: "gcr.io/cloud-builders/gcloud"
    args: [
      'run', 
      'deploy', 
      'sdp4-admin', 
      '--image', 
      'gcr.io/$PROJECT_ID/sdp4-admin', 
      '--region', 'us-central1', 
      '--platform', 'managed', 
      '--allow-unauthenticated'
    ]